version: "3"
services:
  api:
    build:
      dockerfile: ./docker/dev.Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - postgresdb
    networks:
      - gopg

  postgresdb:
    image: postgres:16.1-alpine
    env_file:
        - .env
    # restart: always
    ports:
      - '${DB_PORT}:5432'
    volumes: 
      - dbvol:/var/lib/postgresql/data
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - gopg

volumes:
  dbvol:
    driver: local

networks:
  gopg:
    driver: bridge